// <auto-generated />
using System;
using LogisticsPartnerHub.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LogisticsPartnerHub.Infrastructure.Data.Migrations
{
    [DbContext(typeof(LogisticsPartnerDbContext))]
    partial class LogisticsPartnerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LogisticsPartnerHub.Domain.Entities.FieldMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Direction")
                        .HasColumnType("integer")
                        .HasColumnName("direction");

                    b.Property<Guid>("PartnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("partner_id");

                    b.Property<int>("ServiceType")
                        .HasColumnType("integer")
                        .HasColumnName("service_type");

                    b.Property<string>("SourceField")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("source_field");

                    b.Property<string>("TargetField")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("target_field");

                    b.HasKey("Id");

                    b.HasIndex("PartnerId", "ServiceType", "Direction");

                    b.ToTable("field_mappings", (string)null);
                });

            modelBuilder.Entity("LogisticsPartnerHub.Domain.Entities.Partner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuthConfig")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("auth_config");

                    b.Property<int>("AuthType")
                        .HasColumnType("integer")
                        .HasColumnName("auth_type");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("base_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("partners", (string)null);
                });

            modelBuilder.Entity("LogisticsPartnerHub.Domain.Entities.PartnerEndpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("http_method");

                    b.Property<Guid>("PartnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("partner_id");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("path");

                    b.Property<int>("ServiceType")
                        .HasColumnType("integer")
                        .HasColumnName("service_type");

                    b.HasKey("Id");

                    b.HasIndex("PartnerId", "ServiceType")
                        .IsUnique();

                    b.ToTable("partner_endpoints", (string)null);
                });

            modelBuilder.Entity("LogisticsPartnerHub.Domain.Entities.ServiceOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CanonicalPayload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("canonical_payload");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_id");

                    b.Property<string>("PartnerExternalId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("partner_external_id");

                    b.Property<Guid>("PartnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("partner_id");

                    b.Property<string>("PartnerPayload")
                        .HasColumnType("jsonb")
                        .HasColumnName("partner_payload");

                    b.Property<int>("ServiceType")
                        .HasColumnType("integer")
                        .HasColumnName("service_type");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("PartnerId");

                    b.HasIndex("Status");

                    b.ToTable("service_orders", (string)null);
                });

            modelBuilder.Entity("LogisticsPartnerHub.Domain.Entities.ServiceOrderLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_number");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Direction")
                        .HasColumnType("integer")
                        .HasColumnName("direction");

                    b.Property<int?>("HttpStatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("http_status_code");

                    b.Property<string>("RequestPayload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("request_payload");

                    b.Property<string>("ResponsePayload")
                        .HasColumnType("jsonb")
                        .HasColumnName("response_payload");

                    b.Property<Guid>("ServiceOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_order_id");

                    b.HasKey("Id");

                    b.HasIndex("ServiceOrderId");

                    b.ToTable("service_order_logs", (string)null);
                });

            modelBuilder.Entity("LogisticsPartnerHub.Domain.Entities.FieldMapping", b =>
                {
                    b.HasOne("LogisticsPartnerHub.Domain.Entities.Partner", "Partner")
                        .WithMany("FieldMappings")
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("LogisticsPartnerHub.Domain.Entities.PartnerEndpoint", b =>
                {
                    b.HasOne("LogisticsPartnerHub.Domain.Entities.Partner", "Partner")
                        .WithMany("Endpoints")
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("LogisticsPartnerHub.Domain.Entities.ServiceOrder", b =>
                {
                    b.HasOne("LogisticsPartnerHub.Domain.Entities.Partner", "Partner")
                        .WithMany("ServiceOrders")
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("LogisticsPartnerHub.Domain.Entities.ServiceOrderLog", b =>
                {
                    b.HasOne("LogisticsPartnerHub.Domain.Entities.ServiceOrder", "ServiceOrder")
                        .WithMany("Logs")
                        .HasForeignKey("ServiceOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceOrder");
                });

            modelBuilder.Entity("LogisticsPartnerHub.Domain.Entities.Partner", b =>
                {
                    b.Navigation("Endpoints");

                    b.Navigation("FieldMappings");

                    b.Navigation("ServiceOrders");
                });

            modelBuilder.Entity("LogisticsPartnerHub.Domain.Entities.ServiceOrder", b =>
                {
                    b.Navigation("Logs");
                });
#pragma warning restore 612, 618
        }
    }
}
